# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/painel_clientess
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto do PostgreSQL para JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Atualiza o banco de dados automaticamente (apenas em dev)
spring.jpa.hibernate.ddl-auto=update

